### ISSUE TITLE
CSS KeyFrame Syntax shows error

### ISSUE THREAD

**Issue by chadsevertson** [intersystems/language-server#261]
Type: <b>Bug</b>

Adding the following to a <style> block on a CSP page shows an error. 

```css
@keyframes mapZoom {
		0% {
			transform: scale(0);
		}

		100% {
			transform: scale(1);
		}
	}
```

Extension version: 2.3.0
VS Code version: Code 1.75.0 (Universal) (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin arm64 21.4.0
Modes:
Sandboxed: No

<img width="499" alt="image" src="https://user-images.githubusercontent.com/3631621/218527330-d9399902-bdb9-4e53-a306-96e7dbf70bde.png">
